# Generated by Django 4.0 on 2022-01-28 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Home_content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_eng', models.CharField(max_length=100)),
                ('title_hun', models.CharField(max_length=100)),
                ('text_eng', models.TextField(max_length=1000)),
                ('text_hun', models.TextField(max_length=1000)),
                ('img_src', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='List_of_word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_name', models.CharField(max_length=100)),
                ('list_description', models.TextField(max_length=1000)),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word_away', models.CharField(max_length=100)),
                ('word_home', models.CharField(max_length=100)),
                ('sentence_away', models.TextField(max_length=1000)),
                ('sentence_home', models.TextField(max_length=1000)),
                ('word_description', models.TextField(max_length=1000)),
                ('synonyms', models.CharField(max_length=200)),
                ('learnt', models.BooleanField(default=False)),
                ('list_of_word_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='englishwordcardapp.list_of_word')),
            ],
        ),
    ]
